#!/usr/bin/env bash
# install.sh — install (or REPAIR) cost-tracker on this machine from this checkout.
#
# One command for both first install and recovery. The recovery case is the one that
# motivated it: `joyia agent --setup` rewrites settings.json statusLine to
# `sh ~/.claude/joyia-statusline.sh` (and overwrites that file), after which the status
# line looks fine but captures nothing and every today/saved figure reads $0. Undoing
# that by hand took two sessions on 2026-09-23 and still landed on the wrong target
# (the renderer instead of the capture wrapper). Re-running this is the whole recipe.
#
# What it does, in order:
#   1. install/wire-statusline.sh — points settings.json statusLine straight at
#      <checkout>/bin/cost-ledger-capture.sh, symlinks the ~/.claude/scripts helpers,
#      verifies render + ledger write, rolls back on failure.
#   2. links ~/.local/bin/cost-tracker -> <checkout>/bin/cost-tracker, so the bare name
#      is THIS plugin. A link owned by another tool is reported and replaced (backed up).
#
# It never touches ~/.claude/joyia-statusline.sh: that file is JoyIA's, and it is
# regenerated by `joyia agent --setup` anyway. Only the pointer to it is changed.
set -uo pipefail

usage() {
    cat <<'EOF'
Usage: install.sh [--dry-run] [--help]

Install or repair cost-tracker from this checkout: wire the Claude Code
statusLine to bin/cost-ledger-capture.sh (via install/wire-statusline.sh) and
link ~/.local/bin/cost-tracker to bin/cost-tracker.

With no arguments it does the work (backups first). Re-run it after anything
rewrites your status line, e.g. `joyia agent --setup`. Safe to repeat.

Options:
  --dry-run    report what is wrong and what would change; write nothing
  -h, --help   show this help and exit

Environment:
  HOME                      everything resolves under $HOME
  COST_TRACKER_PLUGIN       force this directory as the plugin root (developer
                            override; must contain .claude-plugin/plugin.json).
                            Skips the cache search and uses this path directly.
  COST_TRACKER_BIN_DIR      where to link the CLI (default: $HOME/.local/bin)

Exit status: 0 done (or nothing to do, or dry run), 1 a step failed, 2 bad usage.
EOF
}

DRY=0
for arg in "$@"; do
    case "$arg" in
        -h|--help) usage; exit 0 ;;
        --dry-run|-n) DRY=1 ;;
        *) printf 'install.sh: unknown argument: %s\n' "$arg" >&2
           printf 'usage: install.sh [--dry-run] [--help]\n' >&2
           exit 2 ;;
    esac
done

# Resolve where this plugin is installed:
#   1. $COST_TRACKER_PLUGIN override (developer/sysadmin pin)
#   2. the highest-versioned entry in the plugin cache (no hardcoded version)
#   3. this checkout (when run directly from the source repo)
ROOT="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RESOLVER="$ROOT/bin/cost-tracker-resolve.sh"
if [ -x "$RESOLVER" ]; then
    RESOLVED="$(bash "$RESOLVER" 2>/dev/null)" && ROOT="$RESOLVED"
fi
BIN_DIR="${COST_TRACKER_BIN_DIR:-$HOME/.local/bin}"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"

say() { printf '%s\n' "$*"; }

say "== 1/2  statusLine wiring"
if [ "$DRY" = "1" ]; then
    bash "$ROOT/install/wire-statusline.sh" --dry-run || exit 1
else
    bash "$ROOT/install/wire-statusline.sh" || exit 1
fi

say ""
say "== 2/2  cost-tracker on PATH"
LINK="$BIN_DIR/cost-tracker"
WANT="$ROOT/bin/cost-tracker"
if [ -L "$LINK" ] && [ "$(readlink "$LINK")" = "$WANT" ]; then
    say "  already linked  $LINK -> $WANT"
else
    if [ -L "$LINK" ]; then
        say "  FOREIGN link    $LINK -> $(readlink "$LINK")"
    elif [ -e "$LINK" ]; then
        say "  FOREIGN file    $LINK (not a symlink)"
    else
        say "  MISSING         $LINK"
    fi
    say "                  -> $WANT"
    if [ "$DRY" = "0" ]; then
        mkdir -p "$BIN_DIR" || { say "cannot create $BIN_DIR"; exit 1; }
        if [ -e "$LINK" ] || [ -L "$LINK" ]; then
            B="$HOME/.claude/backups/cost-tracker-path-$STAMP"
            mkdir -p "$B" && cp -P -p "$LINK" "$B/cost-tracker" || { say "backup failed"; exit 1; }
            say "  backed up the previous entry to $B/cost-tracker"
        fi
        ln -sfn "$WANT" "$LINK" || { say "link failed"; exit 1; }
        say "  linked"
    fi
fi
case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) say "  NOTE  $BIN_DIR is not on PATH in this shell" ;;
esac
if [ "$DRY" = "0" ]; then
    FIRST="$(PATH="$BIN_DIR:$PATH" command -v cost-tracker)"
    if [ "$FIRST" != "$LINK" ]; then
        say "  WARNING  another cost-tracker comes first on PATH: $FIRST"
    fi
fi

say ""
[ "$DRY" = "1" ] && say "DRY RUN — nothing written." || say "Done. The status line picks this up on its next render."
